In [1]:
# install python package - Numpy

In [2]:
# install python package - Numpy
# pip install numpy

In [3]:
import numpy as np

In [4]:
myList=[1, 2, 3, 4]

In [5]:
print(myList)

[1, 2, 3, 4]


In [6]:
type(myList)

list

In [7]:
#dir(np)

In [8]:
#help(np)

In [9]:
arr=np.array(myList)

In [10]:
print(arr)
print(type(arr))

[1 2 3 4]
<class 'numpy.ndarray'>


In [11]:
#shape of the array
arr.shape

(4,)

In [12]:
arr.size

4

In [13]:
my_list1=[1,2,3,4,5]
my_list2=[2,3,4,5,6]
my_list3=[9,7,6,8,9]

arr=np.array([my_list1,my_list2,my_list3])

In [14]:
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [15]:
type(arr)

numpy.ndarray

In [16]:
arr.shape

(3, 5)

In [17]:
arr.size

15

In [18]:
# numpy array indexing

my_list1=[1,2,3,4,5]
arr=np.array(my_list1)


In [19]:
arr

array([1, 2, 3, 4, 5])

In [20]:
print(arr[0])

1


In [21]:
print(arr[1])

2


In [22]:
print('the third element is',arr[2],',','the fourth element is',arr[3])


the third element is 3 , the fourth element is 4


In [23]:
#access 2D array

my_list1=[1,2,3,4,5]
my_list2=[2,3,4,5,6]
my_list3=[9,7,6,8,9]

arr=np.array([my_list1,my_list2,my_list3])

In [24]:
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [25]:
arr[1,2]

4

In [26]:
print('2nd element on 1st row:',arr[0,1])

2nd element on 1st row: 2


In [27]:
#access the element on the 2nd row, 5th column
print('5th element on 2nd row:',arr[1,4])

5th element on 2nd row: 6


In [28]:
#create a 2d array

valArr=np.array([[1,2,3],[4,5,6]])

In [29]:
print('printing the variable value:',valArr)

printing the variable value: [[1 2 3]
 [4 5 6]]


In [30]:
print('printing the size:',valArr.size)

printing the size: 6


In [31]:
print('printing the shape:',valArr.shape)

printing the shape: (2, 3)


In [32]:
print('indexing 1st row 1st element:',valArr[0,0])

indexing 1st row 1st element: 1


In [33]:
print('indexing 2nd row 3rd element:',valArr[0,0])

indexing 2nd row 3rd element: 1


In [34]:
my_l1=[1,2,3,4,5]
my_l2=[6,7,8,9,10]
my_l3=[1,2,3,4,5]
my_l4=[11,12,13,14,15]
my_l5=[20,25,30,35,40]

arr= np.array([my_l1,my_l2,my_l3,my_l4,my_l5])


In [35]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5],
       [11, 12, 13, 14, 15],
       [20, 25, 30, 35, 40]])

In [36]:
arr[3,2]

13

In [37]:
print('2nd element on 1st row:',arr[0,1])

2nd element on 1st row: 2


In [38]:
print('5th element on 2nd row:',arr[1,4])

5th element on 2nd row: 10


In [39]:
#create  a 5*5 array
newArr= np.array([[1,2,3,4,5],[6,7,8,9,10],[1,2,3,4,5],[11,12,13,14,15],[20,25,30,35,40]])

In [40]:
print('printing the variable value:',newArr)

printing the variable value: [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [ 1  2  3  4  5]
 [11 12 13 14 15]
 [20 25 30 35 40]]


In [41]:
print('printing the size:',newArr.size)

printing the size: 25


In [42]:
print('indexing 1st row 1st element:',valArr[0,0])

indexing 1st row 1st element: 1


In [43]:
# Negative indexing

mylist=[1,2,3,4,5,6,7]
arr=np.array(mylist)

#print(arr)

valArr=np.array([[1,2,3],[4,5,6]])
print(valArr)

[[1 2 3]
 [4 5 6]]


In [44]:
valArr[1,-2]

5

In [45]:
valArr[0,-1]

3

In [46]:
#numpy array slicing - 1d

mylist=[1,2,3,4,5,6,7,8]

arr=np.array(mylist)

print(arr)

[1 2 3 4 5 6 7 8]


In [47]:
arr[0:4]

array([1, 2, 3, 4])

In [48]:
arr[0:5]

array([1, 2, 3, 4, 5])

In [49]:
mylist=[1,2,3,4,5,6,7,8,9,10,11,12]
arr=np.array(mylist)

In [50]:
arr[0:]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [51]:
arr[3:]

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12])

In [52]:
arr[:6]

array([1, 2, 3, 4, 5, 6])

In [53]:
arr[:5]

array([1, 2, 3, 4, 5])

In [54]:
arr[:-1]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [55]:
arr[-3:-1]

array([10, 11])

In [56]:
arr[-6:-1]

array([ 7,  8,  9, 10, 11])

In [57]:
arr[::2]

array([ 1,  3,  5,  7,  9, 11])

In [58]:
arr[1::2]

array([ 2,  4,  6,  8, 10, 12])

In [59]:
arr[1::3]

array([ 2,  5,  8, 11])

In [60]:
#slicing 2d array

my_list1=[1,2,3,4,5]
my_list2=[2,3,4,5,6]
my_list3=[9,7,6,8,9]

arr=np.array([my_list1,my_list2,my_list3])
print(arr)

[[1 2 3 4 5]
 [2 3 4 5 6]
 [9 7 6 8 9]]


In [61]:
arr[1:,:]

array([[2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [62]:
arr[:,3:]

array([[4, 5],
       [5, 6],
       [8, 9]])

In [63]:
arr[:,:3]

array([[1, 2, 3],
       [2, 3, 4],
       [9, 7, 6]])

In [64]:
arr[0:1,1:3]

array([[2, 3]])

In [65]:
arr[:,1:4]

array([[2, 3, 4],
       [3, 4, 5],
       [7, 6, 8]])

In [66]:
#arange function


np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [67]:
np.arange(8,16)

array([ 8,  9, 10, 11, 12, 13, 14, 15])

In [68]:
np.arange(10,20,2)

array([10, 12, 14, 16, 18])

In [69]:
# linspace

np.linspace(1,100)

array([  1.        ,   3.02040816,   5.04081633,   7.06122449,
         9.08163265,  11.10204082,  13.12244898,  15.14285714,
        17.16326531,  19.18367347,  21.20408163,  23.2244898 ,
        25.24489796,  27.26530612,  29.28571429,  31.30612245,
        33.32653061,  35.34693878,  37.36734694,  39.3877551 ,
        41.40816327,  43.42857143,  45.44897959,  47.46938776,
        49.48979592,  51.51020408,  53.53061224,  55.55102041,
        57.57142857,  59.59183673,  61.6122449 ,  63.63265306,
        65.65306122,  67.67346939,  69.69387755,  71.71428571,
        73.73469388,  75.75510204,  77.7755102 ,  79.79591837,
        81.81632653,  83.83673469,  85.85714286,  87.87755102,
        89.89795918,  91.91836735,  93.93877551,  95.95918367,
        97.97959184, 100.        ])

In [70]:
#datatype
arr=np.array([1,2,3,4,5])

print(arr.dtype)

int32


In [71]:
arr=np.array([1.2,3.6])
print(arr.dtype)

float64


In [72]:
arr=np.array(['apple','banana','cherry'])
print(arr.dtype)

<U6


In [73]:
arr=np.array(['apple','banana','bananacherry'])
print(arr.dtype)

<U12


In [74]:
arr=np.array([1,2,3,4,5])
print(arr)
print(arr.dtype)


[1 2 3 4 5]
int32


In [75]:
arr=np.array([1,2,3,4,5],dtype='S')
print(arr)
print(arr.dtype)


[b'1' b'2' b'3' b'4' b'5']
|S1


In [76]:
arr=np.array([1,2,3,4,5],dtype=np.int64)
print(arr)
print(arr.dtype)


[1 2 3 4 5]
int64


In [77]:
arr=np.array([1,2,3,4,5],dtype=np.float32)
print(arr)
print(arr.dtype)


[1. 2. 3. 4. 5.]
float32


In [78]:
arr=np.array([1,2,3,4,5],dtype=np.float64)
print(arr)
print(arr.dtype)

[1. 2. 3. 4. 5.]
float64


In [79]:
#array math

x=np.array([[1,2],[3,4]])
y=np.array([[4,6],[7,8]])

In [80]:
print(x)
print(y)

[[1 2]
 [3 4]]
[[4 6]
 [7 8]]


In [81]:
print(x+y)

[[ 5  8]
 [10 12]]


In [82]:
np.add(x,y)

array([[ 5,  8],
       [10, 12]])

In [83]:
print(x-y)

[[-3 -4]
 [-4 -4]]


In [84]:
np.subtract(x,y)

array([[-3, -4],
       [-4, -4]])

In [85]:
print(x*y)

[[ 4 12]
 [21 32]]


In [86]:
np.multiply(x,y)

array([[ 4, 12],
       [21, 32]])

In [87]:
print(x/y)

[[0.25       0.33333333]
 [0.42857143 0.5       ]]


In [88]:
np.divide(x,y)

array([[0.25      , 0.33333333],
       [0.42857143, 0.5       ]])

In [89]:
np.square(x,y)

array([[ 1,  4],
       [ 9, 16]])

In [90]:
np.sqrt(x)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

In [91]:
x=np.array([[1,2],[3,4]])
y=np.array([[4,6],[7,8],[9,10]])

In [92]:
np.add(x,y)

ValueError: operands could not be broadcast together with shapes (2,2) (3,2) 

In [ ]:
np.exp(x)

In [ ]:
np.log(x)

In [ ]:
np.cos(x)

In [ ]:
np.tan(x)

In [ ]:
#floor, ceil, round
x=np.array([[1.5,2.6],[3.1,4.9]])

In [ ]:
x

In [ ]:
np.floor(x)

In [ ]:
np.ceil(x)

In [ ]:
np.round(x)

In [ ]:
# numpy array copy vs view
arr=np.array([1,2,3,4,5])
x=arr

In [ ]:
print(arr)

In [ ]:
print(x)

In [ ]:
arr[0]

In [ ]:
arr[0]=100

In [ ]:
print(arr)

In [ ]:
print(x)

In [ ]:
x[1]=200

In [ ]:
print(x)

In [ ]:
print(arr)

In [ ]:
#numpy array copy
# numpy array copy vs view
arr=np.array([1,2,3,4,5])
x=arr.copy()

In [ ]:
print(arr)

In [ ]:
print(x)

In [ ]:
arr[0]=100

In [ ]:
print(arr)

In [ ]:
print(x)

In [ ]:
x[1]=200

In [ ]:
print(x)

In [ ]:
print(arr)

In [94]:
#numpy array reshaping
arr=np.arange(1,13)
arr.shape

(12,)

In [95]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [96]:
arr.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [97]:
arr.reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [98]:
arr_new=arr.reshape(4,3)

In [99]:
arr_new

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [100]:
#flattening the arrays
#2d to 1d
arr_new.reshape(-1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [101]:
arr_new.reshape(-1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [104]:
np.arange(1,7).reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [106]:
np.arange(1,7).reshape(3,2).sum()

21

In [107]:
np.arange(1,7).reshape(3,2).sum(axis=0)

array([ 9, 12])

In [110]:
#iterating array
arr=np.arange(1,7).reshape(3,2)

In [111]:
arr

array([[1, 2],
       [3, 4],
       [5, 6]])

In [112]:
for x in arr:
    print(x)

[1 2]
[3 4]
[5 6]


In [113]:
#joining numpy arrays 1d
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])

In [114]:
np.concatenate((arr1,arr2))

array([1, 2, 3, 4, 5, 6])

In [117]:
#joining numpy arrays 2d
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])

In [118]:
np.concatenate((arr1,arr2))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])